/* Verilog module instantiation template generated by SCUBA Diamond_1.4_Production (80) */
/* Module Version: 2.4 */
/* Sat Mar 10 21:49:22 2012 */

/* parameterized module instance */
LCDCharMapLUTs __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), 
    .Q( ));
