/* Verilog module instantiation template generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 1.0 */
/* Wed Mar 14 17:04:39 2012 */

/* parameterized module instance */
efb_spi_i2c __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .i2c1_scl( ), .i2c1_sda( ), .i2c1_irqo( ), .i2c2_scl( ), 
    .i2c2_sda( ), .i2c2_irqo( ), .spi_clk( ), .spi_miso( ), .spi_mosi( ), 
    .spi_scsn( ), .ufm_sn( ), .wbc_ufm_irq( ), .cfg_wake( ), 
    .cfg_stdby( ));
