/* Verilog netlist generated by SCUBA Diamond_1.4_Production (80) */
/* Module Version: 2.4 */
/* C:\lscc\diamond\1.4\ispfpga\bin\nt\scuba.exe -w -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type rom -addr_width 6 -num_rows 64 -data_width 8 -outdata REGISTERED -memfile c:/joem/xo2_ae_projects/xo2_pico_ae7/hardware/source/picolcddriver/lcdcharmapluts.mem -memformat bin -e  */
/* Sat Mar 10 21:49:22 2012 */


`timescale 1 ns / 1 ps
module LCDCharMapLUTs (Address, OutClock, OutClockEn, Reset, Q);
    input wire [5:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [7:0] Q;

    wire qdataout7_ffin;
    wire qdataout6_ffin;
    wire qdataout5_ffin;
    wire qdataout4_ffin;
    wire qdataout3_ffin;
    wire qdataout2_ffin;
    wire qdataout1_ffin;
    wire qdataout0_ffin;

    FD1P3DX FF_7 (.D(qdataout7_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(qdataout6_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(qdataout5_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(qdataout4_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    defparam mem_0_7.initval =  64'h0000000000000000 ;
    ROM64X1A mem_0_7 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout7_ffin));

    defparam mem_0_6.initval =  64'hC304B440C12D1083 ;
    ROM64X1A mem_0_6 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout6_ffin));

    defparam mem_0_5.initval =  64'hE823308A08CC208E ;
    ROM64X1A mem_0_5 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout5_ffin));

    defparam mem_0_4.initval =  64'hFE505007941402BA ;
    ROM64X1A mem_0_4 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout4_ffin));

    defparam mem_0_3.initval =  64'hE03B1A100EC68492 ;
    ROM64X1A mem_0_3 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout3_ffin));

    defparam mem_0_2.initval =  64'hAEA8C34BAA30D004 ;
    ROM64X1A mem_0_2 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout2_ffin));

    defparam mem_0_1.initval =  64'hE8E3C76238F1D860 ;
    ROM64X1A mem_0_1 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout1_ffin));

    defparam mem_0_0.initval =  64'hF7A2B8A5E8AE2812 ;
    ROM64X1A mem_0_0 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(qdataout0_ffin));



    // exemplar begin
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
