/* Verilog module instantiation template generated by SCUBA Diamond_1.4_Production (80) */
/* Module Version: 5.0 */
/* Wed Feb 29 13:10:01 2012 */

/* parameterized module instance */
LCDCharMap __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), 
    .Q( ));
