/* Verilog netlist generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 1.0 */
/* C:\lscc\diamond\1.4\ispfpga\bin\nt\scuba.exe -w -n pwr_ctrl -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type power_cntl -entry CFG -s2s BYPASS -wake CFG -standby -e  */
/* Thu Mar 08 11:50:11 2012 */


`timescale 1 ns / 1 ps
module pwr_ctrl (CLRFLAG, CFGSTDBY, CFGWAKE, STDBY, SFLAG);
    input wire CLRFLAG;
    input wire CFGSTDBY;
    input wire CFGWAKE;
    output wire STDBY;
    output wire SFLAG;

    wire scuba_vlo;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam PCNTR_Inst0.BGOFF = "FALSE" ;
    defparam PCNTR_Inst0.POROFF = "FALSE" ;
    defparam PCNTR_Inst0.WAKEUP = "CFG" ;
    defparam PCNTR_Inst0.TIMEOUT = "BYPASS" ;
    defparam PCNTR_Inst0.STDBYOPT = "CFG" ;
    PCNTR PCNTR_Inst0 (.CLK(scuba_vlo), .USERTIMEOUT(scuba_vlo), .USERSTDBY(scuba_vlo), 
        .CLRFLAG(CLRFLAG), .CFGSTDBY(CFGSTDBY), .CFGWAKE(CFGWAKE), .STOP(), 
        .STDBY(STDBY), .SFLAG(SFLAG));



    // exemplar begin
    // exemplar end

endmodule
