/* Verilog module instantiation template generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 1.0 */
/* Thu Mar 08 11:50:11 2012 */

/* parameterized module instance */
pwr_ctrl __ (.CLRFLAG( ), .CFGSTDBY( ), .CFGWAKE( ), .STDBY( ), 
    .SFLAG( ));
