/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 5.0 */
/* Thu Apr 07 23:20:54 2011 */

/* parameterized module instance */
LCDCharMap __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), 
    .Q( ));
