wave scl
wave sda
wave dut/LCD_wb_adr
wave dut/LCD_wb_wr_data
wave dut/LCD_wb_rd_data
wave dut/LCD_wb_stb
wave dut/LCD_wb_cyc
wave dut/LCD_wb_we
wave dut/LCD_wb_ack
wave dut/EFB_wb_adr
wave dut/EFB_wb_wr_data
wave dut/EFB_wb_rd_data
wave dut/EFB_wb_stb
wave dut/EFB_wb_cyc
wave dut/EFB_wb_we
wave dut/EFB_wb_ack
wave dut/EFB_i2c_irq
wave dut/mico8_u/LM8/pc
wave dut/mico8_u/LM8/I_ACK_I
wave dut/mico8_u/LM8/I_ERR_I
wave dut/mico8_u/LM8/I_RTY_I
wave dut/mico8_u/LM8/I_DAT_I
wave dut/mico8_u/LM8/I_CYC_O
wave dut/mico8_u/LM8/I_STB_O
wave dut/mico8_u/LM8/I_CTI_O
wave dut/mico8_u/LM8/I_BTE_O
wave dut/mico8_u/LM8/I_WE_O
wave dut/mico8_u/LM8/I_SEL_O
wave dut/mico8_u/LM8/I_DAT_O
wave dut/mico8_u/LM8/I_ADR_O
wave dut/mico8_u/LM8/I_LOCK_O
wave dut/mico8_u/LM8/D_ACK_I
wave dut/mico8_u/LM8/D_ERR_I
wave dut/mico8_u/LM8/D_RTY_I
wave dut/mico8_u/LM8/D_DAT_I
wave dut/mico8_u/LM8/D_CYC_O
wave dut/mico8_u/LM8/D_STB_O
wave dut/mico8_u/LM8/D_CTI_O
wave dut/mico8_u/LM8/D_BTE_O
wave dut/mico8_u/LM8/D_WE_O
wave dut/mico8_u/LM8/D_SEL_O
wave dut/mico8_u/LM8/D_DAT_O
wave dut/mico8_u/LM8/D_ADR_O
wave dut/mico8_u/LM8/D_LOCK_O
