CC = lm8-elf-gcc
CFLAGS+= -ffunction-sections -mcall-prologues -O1 -Wall -D__MICO_NO_INTERRUPTS__ -D__MICOEFB_NO_I2C_INTERRUPT__ -D__MICOEFB_NO_SPI_INTERRUPT__ -D__MICOEFB_NO_TC_INTERRUPT__
PLATFORM_LIBRARY_OUTPUT_DIR = ../../Release/Release
PLATFORM_LIBRARY_NAME=mico8
PLATFORM_BUILD_CFG=Release
