/* Verilog module instantiation template generated by SCUBA Diamond_1.4_Production (80) */
/* Module Version: 1.0 */
/* Tue Mar 06 00:03:34 2012 */

/* parameterized module instance */
machxo2_efb __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .i2c1_scl( ), .i2c1_sda( ), .i2c1_irqo( ), .spi_clk( ), .spi_miso( ), 
    .spi_mosi( ), .spi_scsn( ), .spi_csn( ));
